extends:
  - "spectral:oas"

rules:
  # ---------------------------------------------------------------------------
  # Schema rules
  # ---------------------------------------------------------------------------
  info-version-semver:
    severity: error
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version.
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+\\.[0-9]+\\.[0-9]+)$"

  # ---------------------------------------------------------------------------
  # API Rules
  # ---------------------------------------------------------------------------
  server-url-must-contain-version:
    description: Global API version must be present in the path
    severity: error
    recommended: true
    message: "Unversioned server URL detected: {{value}}"
    given: "$.servers[*].url"
    then:
      function: pattern
      functionOptions:
        match: "\/v[1-9]+\/"

  paths-kebab-case:
    description: Paths should be kebab-case.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9_]+})+$"

  field-names-snake-case:
    description: Property names must be in snake_case (lowercase with underscores).
    message: "{{property}} must be in snake_case."
    severity: error
    given: "$..properties[*]~"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-z0-9_]*$"

  error-responses-must-have-code-and-message:
    description: Error responses must include 'code' and 'message' properties.
    severity: error
    message: "Error responses must define 'code' and 'message'."
    given: "$.paths[*][*].responses[?(@property >= 400)].content.application/json.schema.properties"
    then:
      function: schema
      functionOptions:
        required:
          - code
          - message

  error-500-401-403-must-have-code-and-message:
    description: 500, 401, and 403 responses must include 'code' and 'message' properties.
    severity: error
    message: "Error {{property}} response must include 'code' and 'message' fields."
    given: "$.paths[*][*].responses[?( @property == '500' || @property == '401' || @property == '403' )].content.application/json.schema.properties"
    then:
      function: schema
      functionOptions:
        required:
          - code
          - message

  must-define-common-error-responses:
    description: All endpoints must define 401, 403, and 500 error responses.
    severity: error
    message: "Endpoint must define standard error responses: 401, 403, and 500."
    given: "$.paths[*][*].responses"
    then:
      function: schema
      functionOptions:
        required:
          - '401'
          - '403'
          - '500'

  required-fields-must-have-examples:
    description: All required fields in request bodies must have examples.
    severity: warn
    message: "Required field '{{property}}' must have an example."
    given: "$.components.schemas[*].properties[?(@ && @.example == undefined)]"
    then:
      function: truthy

  operation-id-snake-case:
    description: OperationId must be in snake_case.
    severity: warn
    given: "$.paths[*][*].operationId"
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-z0-9_]*$"

  operation-id-unique:
    description: Operation IDs must be unique.
    severity: error
    given: "$.paths[*][*].operationId"
    then:
      function: uniqueness

  tag-used:
    description: Each operation must be tagged for grouping in the API documentation.
    severity: error
    given: "$.paths[*][*]"
    then:
      field: tags
      function: truthy

  summary-and-description-required:
    description: All operations must have summary and description.
    severity: error
    given: "$.paths[*][*]"
    then:
      function: schema
      functionOptions:
        required:
          - summary
          - description

  security-schemes-defined:
    description: All operations must define security requirements.
    severity: error
    given: "$.paths[*][*]"
    then:
      field: security
      function: truthy

  successful-response-must-be-json:
    description: Successful responses must use application/json.
    severity: error
    given: "$.paths[*][*].responses[?(@property >= 200 && @property < 300)].content"
    then:
      function: schema
      functionOptions:
        required:
          - application/json

  no-empty-response-schema:
    description: Response schemas must not be empty.
    severity: error
    given: "$.paths[*][*].responses[*].content.application/json.schema"
    then:
      function: defined